-- Seed inventory_items from procurement Google Sheet (67 items).
-- Categories mapped to the app taxonomy (microcontroller/motor/sensor/battery/chassis/tool/cable/general).
-- Idempotent: skips any item whose name already exists. Safe to re-run.
-- Run in the Supabase SQL Editor.

INSERT INTO inventory_items (name, category, description, total_quantity, available_quantity, is_consumable)
SELECT v.name, v.category, v.description, v.total_quantity, v.available_quantity, v.is_consumable
FROM (VALUES
  ('18650 2 cell holder charger', 'battery', 'Brand: Customized / Model: 18650', 16, 16, false)
, ('XT30 Connector', 'cable', NULL, 50, 50, true)
, ('Motor Driver-L293D L298D L298N', 'motor', NULL, 50, 50, true)
, ('Drill - Mounted Vertical', 'tool', 'Brand: DRILL PRESS / Model: VOLTZ', 1, 1, false)
, ('8GB Nvidia Jetson Orin Nano Deplyment Kit', 'microcontroller', 'Brand: NVIDIA / Model: SBC1116', 2, 2, false)
, ('Bambu Lab Hotend with stainless steel nozzle-0.2 mm', 'general', 'Brand: Bambu Lab', 2, 2, true)
, ('12v tool battery', 'battery', 'Brand: Bosch / Model: 1600A022V3', 4, 4, false)
, ('BLDC Motors-1000KV', 'motor', NULL, 24, 24, false)
, ('Edge AI Device With Nvidia Jetson Orein-NX 16GB Module', 'microcontroller', 'Brand: NVIDIA / Model: SBC1045', 4, 4, false)
, ('Blower cordless', 'tool', 'Brand: BOSCH / Model: 06019F5100', 1, 1, false)
, ('Orbit Sander Cordless', 'tool', 'Brand: Bosch / Model: 06013A5080', 2, 2, false)
, ('Depth Camera - Intel D435i', 'sensor', 'Brand: Intel / Model: 82635DSD455', 2, 2, false)
, ('H2D Combo 1', 'tool', 'Brand: Bambu Lab / Model: H2D', 1, 1, false)
, ('4 Wheel D Chassis Kits', 'chassis', 'Brand: Customized', 10, 10, false)
, ('BreadBoard-Regular (High Quality)', 'general', NULL, 50, 50, true)
, ('Dremel tool', 'tool', 'Brand: Bosch / Model: 06019C5002', 4, 4, false)
, ('Raspberry Pi5 8gb RAM Module', 'microcontroller', 'Brand: Raspberry / Model: PI5', 26, 26, false)
, ('Arduino UNO SMD Clones PB+232', 'microcontroller', NULL, 30, 30, false)
, ('Official Raspberry Pi Ai HAT+26 TOPS (481)', 'microcontroller', 'Brand: Raspberry', 2, 2, false)
, ('NEMA 17 Stepper Motors 40mm-4KG', 'motor', NULL, 8, 8, false)
, ('Bambu Lab A1 3D Printer', 'tool', 'Brand: Bambu Lab / Model: A1', 2, 2, false)
, ('18v tool battery', 'battery', 'Brand: Bosch / Model: 1600A022V2', 2, 2, false)
, ('ESP32-DevKitC V4', 'microcontroller', NULL, 36, 36, false)
, ('eSun PLA+ 1.75mm 3D Printing Filament 1kg- white', 'general', 'Brand: Customized / Model: eSun', 4, 4, true)
, ('MG90S Metal Gear Motor', 'motor', 'Brand: Customized / Model: MG90S', 50, 50, false)
, ('Servo-MG995-180', 'motor', NULL, 72, 72, false)
, ('CNC Controller Board - 6 Axis', 'microcontroller', 'Brand: Robocraze / Model: TIFC00221', 1, 1, false)
, ('IMU', 'sensor', 'Model: BNO-055/MPU9250', 6, 6, false)
, ('Rulers - 1 ft', 'general', 'Brand: Qatalitic', 24, 24, true)
, ('Toy PCB 4x6 CH340 No.19 (D/E)-XT60', 'general', NULL, 100, 100, true)
, ('Cutter - Handheld', 'tool', 'Brand: Bosch / Model: 06013A41F0', 2, 2, false)
, ('30 A Brushed ESC No Brake', 'motor', 'Brand: Customized / Model: 30A', 5, 5, true)
, ('Teensy 4.0 Board', 'microcontroller', NULL, 2, 2, false)
, ('Raspberry Pi 500 Unit', 'microcontroller', 'Brand: Raspberry / Model: PI500', 1, 1, false)
, ('Raspberry Pi SSD Kit 256gb', 'microcontroller', NULL, 1, 1, false)
, ('Arduino Mega 2560 Rev 3', 'microcontroller', NULL, 12, 12, false)
, ('Raspberry Pi Zero 2', 'microcontroller', NULL, 2, 2, false)
, ('Node MCU', 'microcontroller', NULL, 30, 30, false)
, ('Gloves', 'general', NULL, 8, 8, true)
, ('Ceramic Capacitor 100k pf', 'general', 'Brand: Customized / Model: Customized', 3500, 3500, true)
, ('Bosch GKS 185-LI Professional  18V Brushless Motor', 'tool', 'Brand: Bosch / Model: 06016C12L1', 2, 2, false)
, ('Anvil', 'tool', 'Brand: H. M. TOOLS INDUSTRIES / Model: HM 035', 1, 1, false)
, ('Drill - Handheld', 'tool', 'Brand: Bosch / Model: GSB 500 RE Kit', 2, 2, false)
, ('ESC-30A/40A', 'motor', NULL, 30, 30, true)
, ('Arduino Uno R4 WiFi', 'microcontroller', NULL, 2, 2, false)
, ('Orbit Sander', 'tool', 'Brand: Bosch / Model: 06013A80F0', 2, 2, false)
, ('Digital Oscilloscope', 'tool', 'Brand: Siglent / Model: SDS814X HD', 2, 2, false)
, ('Screw Driver - Electric', 'tool', 'Brand: Bosch / Model: GO 3 (KIT)', 3, 3, false)
, ('Power Supply SMPS 3010S- Vartech', 'battery', NULL, 3, 3, false)
, ('64gb Ultra Sandisk Micro SD Card 10 A1 120M/B', 'general', 'Brand: Sandisk', 40, 40, true)
, ('BO Motors-Dual Sided', 'motor', NULL, 68, 68, false)
, ('Bambu Lab Hotend with hardened steel nozzle-0.4 mm', 'general', 'Brand: Bambu Lab', 4, 4, true)
, ('Bench Grinder - Mounted', 'tool', 'Brand: BOSCH / Model: GBG 35-15', 2, 2, false)
, ('PMDC Geared Motors-300 RPM', 'motor', NULL, 24, 24, false)
, ('Jigsaw', 'tool', 'Brand: BOSCH / Model: 06015B40F0', 4, 4, false)
, ('Breadboards GL-12', 'general', 'Brand: Customized / Model: Customized', 75, 75, true)
, ('Jigsaw Cordless', 'tool', 'Brand: BOSCH / Model: GST 185-Li Professional', 2, 2, false)
, ('Angle Grinder - Handheld cordless', 'tool', 'Brand: BOSCH / Model: GWS 180-LI PROFESSIONAL', 2, 2, false)
, ('Drill cordless 18v', 'tool', 'Brand: Bosch / Model: GSB 185-Li Professional Kit', 1, 1, false)
, ('XT90', 'cable', NULL, 30, 30, true)
, ('Stepper Motor-4KG', 'motor', NULL, 36, 36, false)
, ('Capacitor 100uf/63v', 'general', 'Brand: Customized / Model: Customized', 3500, 3500, true)
, ('Jeston Nano Deployment Kit (B01-4GB)', 'microcontroller', 'Brand: NVIDIA / Model: SBC2067', 2, 2, false)
, ('ESP32-CAM WiFi Bluetooth Camera Module', 'microcontroller', 'Brand: Customized / Model: ESP32', 5, 5, false)
, ('IC AT MEGA 328 PU', 'microcontroller', NULL, 30, 30, true)
, ('Arduino Nano LoT', 'microcontroller', NULL, 2, 2, false)
, ('Bambu Lab H2D Hardened Steel Hotend-0.4mm', 'general', 'Brand: Bambu Lab', 4, 4, true)
) AS v(name, category, description, total_quantity, available_quantity, is_consumable)
WHERE NOT EXISTS (SELECT 1 FROM inventory_items i WHERE i.name = v.name);
